Use cookie to successfully login
JiayangWu/LeetCodeCN-Submissions-Crawler pull request #45
Opened 2023-09-03 16:00 UTC by david990917

Dear all, I have added this cookie interface for login. From my test, it is feasible to use. Could you help to check and merge it?

2023-09-05 04:29 UTC, JiayangWu requested changes
感谢贡献！

还需要修改的部分有：
1. config-example.json。需要删除用户名和密码并新增cookie
2. README里需要更新使用说明和新增版本改动记录

2023-09-05 04:29 UTC, JiayangWu commented on main.py
>  parser.add_argument('-pw', '--password', type=str, help="Your login password")
需要删除掉跟用户名和密码相关的代码。

2023-09-05 04:29 UTC, JiayangWu commented on src/crawler.py
>              self.PASSWORD = args.password if args.password else config['password']
需要删除掉跟用户名和密码相关的代码。

2023-09-05 04:29 UTC, JiayangWu commented on src/leetcode_client.py
>          self.login_id = login_id
需要删除掉跟用户名和密码相关的代码。

2023-09-05 07:30 UTC, david990917 commented on src/leetcode_client.py
>          self.login_id = login_id
请问我们是直接删掉吗？ 还是留一份作为备份

2023-09-05 17:44 UTC, JiayangWu commented on src/leetcode_client.py
>          self.login_id = login_id
> 请问我们是直接删掉吗？ 还是留一份作为备份

直接删就好了，如果LC初次登录需要验证码机制不改，那么仅靠用户名和密码就无法登陆。

2023-09-05 18:48 UTC, david990917 commented
更新完成，并且通过实际执行可以成功运行 @JiayangWu

2023-09-11 03:13 UTC, JiayangWu commented
我小改了一下用cookie登录的方式，之前你是在header里放cookie，但是我这边用这种方法是无法登陆的。所以我改成了手动设置session里的cookie，这样可以登陆成功并正确运行。

2023-09-11 03:13 UTC, merged